use crate::model::TaskflowStatus;
use crate::TaskflowEngine;
use aegis_core::Result;
use std::fmt::Write;

impl TaskflowEngine {
    pub fn render_roadmap(&self) -> Result<String> {
        let index = self.get_status()?;
        let mut out = String::new();

        writeln!(out, "# AegisCore — Roadmap").unwrap();
        writeln!(out, "\n**Note:** This file is auto-generated by `aegis taskflow sync`. Manual changes may be overwritten.").unwrap();

        let mut m_keys: Vec<_> = index.milestones.keys().collect();
        m_keys.sort();

        for m_id in m_keys {
            let milestone = self.get_milestone(m_id)?;
            writeln!(out, "\n## Milestone {} — {}", milestone.id, milestone.name).unwrap();
            if let Some(lld) = &milestone.lld {
                writeln!(out, "**LLD:** `{}`", lld).unwrap();
            }
            writeln!(out, "**Status:** `{}`", milestone.status).unwrap();

            writeln!(out, "\n| # | Task | Status | Notes |").unwrap();
            writeln!(out, "|---|---|---|---|").unwrap();

            for task in milestone.tasks {
                let status_str = match task.status {
                    TaskflowStatus::Done => "done",
                    TaskflowStatus::InProgress => "in-progress",
                    TaskflowStatus::LldDone => "lld-done",
                    TaskflowStatus::LldInProgress => "lld-in-progress",
                    TaskflowStatus::Pending => "pending",
                    TaskflowStatus::Blocked => "blocked",
                };
                writeln!(
                    out,
                    "| {} | {} | `{}` | {} |",
                    task.id,
                    task.task,
                    status_str,
                    task.notes.as_deref().unwrap_or("")
                )
                .unwrap();
            }
        }

        Ok(out)
    }

    pub fn generate_roadmap_file(&self) -> Result<()> {
        let content = self.render_roadmap()?;
        let path = self
            .storage()
            .designs_dir()
            .join("roadmap")
            .join("roadmap.md");
        std::fs::write(&path, content)
            .map_err(|e| aegis_core::AegisError::StorageIo { path, source: e })
    }
}
