// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentStatus } from "./AgentStatus";
import type { ChannelKind } from "./ChannelKind";
import type { DetectedEvent } from "./DetectedEvent";
import type { WatchdogAction } from "./WatchdogAction";

export type AegisEvent = { "type": "agent_spawned", agent_id: string, role: string, } | { "type": "agent_status_changed", agent_id: string, old_status: AgentStatus, new_status: AgentStatus, } | { "type": "task_complete", task_id: string, receipt_path: string, } | { "type": "watchdog_alert", event: DetectedEvent, action: WatchdogAction, } | { "type": "system_notification", message: string, } | { "type": "agent_terminated", agent_id: string, reason: string, } | { "type": "failover_initiated", agent_id: string, from_provider: string, to_provider: string, } | { "type": "task_assigned", task_id: string, agent_id: string, } | { "type": "channel_added", channel_name: string, channel_type: ChannelKind, } | { "type": "channel_removed", channel_name: string, };
