// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentKind } from "./AgentKind";
import type { AgentStatus } from "./AgentStatus";

export type Agent = { agent_id: string, name: string, kind: AgentKind, status: AgentStatus, role: string, parent_id: string | null, task_id: string | null, tmux_session: string, tmux_window: number, tmux_pane: string, worktree_path: string, cli_provider: string, fallback_cascade: Array<string>, sandbox_profile: string, log_path: string, created_at: string, updated_at: string, terminated_at: string | null, };
