// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelKind } from "./ChannelKind";

export type ChannelRecord = { name: string, kind: ChannelKind, active: boolean, registered_at: string, config: unknown, };
