// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DetectedEvent = { "category": "rate_limit", agent_id: string, matched_pattern: string, } | { "category": "auth_failure", agent_id: string, matched_pattern: string, } | { "category": "cli_crash", agent_id: string, exit_code: number | null, } | { "category": "sandbox_violation", agent_id: string, matched_pattern: string, } | { "category": "task_complete", agent_id: string, matched_pattern: string, };
