// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WatchdogAction = "initiate_failover" | "pause_and_notify" | "capture_and_mark_failed" | "log_and_continue" | "trigger_receipt_processing";
