[[tasks]]
id = "B1"
uid = "7db4179f-61a6-4443-b32c-066b03061bc5"
task = "Fix project status 'unknown' in CLI"
task_type = "bug"
status = "done"

[[tasks]]
id = "B2"
uid = "ae798e95-0489-4005-a084-2839ccb0d9ae"
task = "Persist Web UI state in URL paths to prevent state loss on reload"
task_type = "bug"
status = "done"
